version: '2'

services:

  c9:
    build:
      context: .
    # expects environment variables to exist in .env but will run without authentication if absent
    command: ["--auth", "${C9_USER}:${C9_PASS}"]
    ports:
      - "8000:80"
      # "run" configuration ports
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
    volumes:
      - ssh:/root/.ssh
      - c9:/root/.c9
      - envs:/root/.envs

volumes:
  ssh:
  c9:
  envs:
